version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.0
    working_directory: ~/project

    steps:
      - checkout
      - run: java --version
      - run: mvn --version
      - run:
          name: Maven Build command
          command: |
            mvn clean install

workflows:
  version: 2
  build:
    jobs:
      - build