version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.6.3-jdk-17
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Build with Maven Wrapper
          command: |
            mvn clean install

workflows:
  version: 2
  build:
    jobs:
      - build