version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Use an image with Java 8
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Build with Maven Wrapper
          command: |
            ./mvnw clean install

workflows:
  version: 2
  build:
    jobs:
      - build